export interface AllDetails {
    hotel_id : number
	hotel_name : string
	location : string
	hotel_description : string
	amenity_id : number
	amenity_name : string
	amenity_description : string
	room_id : number
	room_number : number
	is_available : Boolean
	reservation_id : number
	guest_name : string
	guest_email : string
	guest_phone : string
	check_in_date : Date
	check_out_date : Date
	payment_id : number
	amount : number
	payment_date : Date
	payment_status  : string
	review_id : number
	rating : number
	comment  : string
	review_date : Date
	room_type_id : number
	type_name  : string
	room_description  : string
	max_occupancy : number
	price_per_night : number
}
